web2/rabbit_delivery/models.py
from rabbit_delivery import db

'''
model.py
이 파일은 데이터베이스의 제약 조건을 명시하는 파일입니다.
관계형 데이터베이스의 데이터를 객체랑 연결 시켜주는 것을 ORM (Object Relational Mapping) 이라고 불러요.
즉, 이 파일은 외부에 존재하는 DB를 서버에서 사용하기 위해, DB와 동일한 제약조건을 객체에 걸어버리는 겁니다.
'''

class rabbitUser(db.Model):

    __tablename__ = 'rabbitUser' # 테이블 이름입니다. 객체 이름과 달라도 되지만, 외부 테이블의 이름이 되기 때문에 유의해서 설정하세요.

    id          = db.Column(db.String(20), primary_key=True, nullable=False) 
    password    = db.Column(db.String(255), nullable=False)
    nickname    = db.Column(db.String(20))
    point       = db.Column(db.Integer)
    address     = db.Column(db.String(255))
    telephone   = db.Column(db.String(11))
    rank        = db.Column(db.Integer)

    def __init__(self, id, password, nickname, telephone):
        self.id         = id
        self.password   = password
        self.nickname   = nickname
        self.telephone  = telephone
        self.point      = 0
        self.rank       = 0


class rabbitStore(db.Model):
    
    __tablename__ = 'rabbitStore'
    
    id          = db.Column(db.Integer, primary_key=True, nullable=False, autoincrement=True)
    name        = db.Column(db.String(20), nullable=False)
    location    = db.Column(db.String(50))
    rating      = db.Column(db.Integer)
    open_time   = db.Column(db.String(5))
    close_time  = db.Column(db.String(5))
    stars       = db.Column(db.Integer)
    thumbnail   = db.Column(db.String(255))


class rabbitMenu(db.Model):

    __tablename__ = 'rabbitMenu'

    id          = db.Column(db.Integer, primary_key=True, nullable=False, autoincrement=True)
    food_name   = db.Column(db.String(20), nullable=False)
    store_id    = db.Column(db.Integer, db.ForeignKey('rabbitStore.id')) # 외부키를 사용할 때는 '테이블 이름.속성' 을 사용해야 합니다. 객체 이름이 아니에요!
    description = db.Column(db.String(255))
    price       = db.Column(db.Integer, nullable=False)
    thumbnail   = db.Column(db.String(255))


class rabbitReview(db.Model):

    __tablename__ = 'rabbitReview'

    id          = db.Column(db.Integer, primary_key=True, nullable=False, autoincrement=True)
    user_id     = db.Column(db.Integer, db.ForeignKey('rabbitUser.id'), nullable=False)
    store_id    = db.Column(db.Integer, db.ForeignKey('rabbitStore.id'), nullable=False)
    rating      = db.Column(db.Float)
    content     = db.Column(db.Text())

web2/rabbit_delivery/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import config


db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config.from_object(config) # config 에서 가져온 파일을 사용합니다.

    db.init_app(app) # SQLAlchemy 객체를 app 객체와 이어줍니다.
    Migrate().init_app(app, db)

    from .views import main_view
    from . import models
    app.register_blueprint(main_view.bp)

    app.secret_key = "seeeeeeeeeeeecret"
    app.config['SESSION_TYPE'] = 'filesystem'

    '''
    세션을 사용하기 위해선, 보안을 위해 세션을 암호화해야 합니다.

    암호화 하는 과정에서 사용하는 비밀 키가 app.secret_key 입니다.

    따라서, 실제 서버를 사용하기 위해선 github 같은 곳에 secret_key를 절대!!! 올려선 안 됩니다.
    이후 여러분들이 서버를 실제 배포 (Apache나 Nginx)를 사용할 때는 파일을 분리하거나, 환경 변수를 설정하는 방식으로
    secret_key가 절대 깃에 노출되지 않도록 해야 합니다.

    그렇다면 SESSION_TYPE = 'filesystem'은 무슨 역할일까요?
    
    세션 정보를 별도의 파일로 뺄 수도 있고, DB에 저장할 수도 있습니다. (flask 에서는 sqlalchemy, redis/mongodb 같은 설정이 가능합니다.)
    그런데 세션을 DB로 관리하기 위해선, 별도의 구조를 만들어야겠죠?
    현재 상황에선 그런 부분을 피하기 위해 filesystem으로 관리합니다.
    '''
    
    return app

if __name__ == "__main__":
    create_app().run()

web2/rabbit_delivery/views/main_view.py
from flask import Blueprint, render_template, request, url_for, session, flash
from rabbit_delivery.models import *
from werkzeug.utils import redirect
from bcrypt import hashpw, checkpw, gensalt

'''
view는 우리 눈에 보이는 부분을 관리합니다.

지난 시간에 작업했을 때는 view를 여러 파일로 분리하지 않았는데, 상황에 따라 파일을 분리할 수 있습니다.
그러면 어떻게 관리하냐고요?

어차피 각 파일마다 별도의 Blueprint를 만들테니, __init__.py에서 전부 import 하고
각각 다 register_blueprint를 활용해서 이어줍니다.

추가로, 코드를 보다보면 query를 사용한 것이 많은데, 이를 활용하면 SQL 구문을 직접 사용하지 않고
ORM을 통해 간접적으로 db에 작업 명령을 내릴 수 있습니다.
'''

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def home():
    store_list = rabbitStore.query.order_by(rabbitStore.name.asc())
    return render_template('main.html', store_list=store_list)

@bp.route('/store/<int:store_id>/')
def store_detail(store_id):
    store_info = rabbitStore.query.filter_by(id=store_id).first()
    store_menu = rabbitMenu.query.filter_by(store_id=store_id).all()
    store_review = rabbitReview.query.filter_by(store_id=store_id).all()
    return render_template('store_detail.html', store_info=store_info, store_menu=store_menu,
    review_info=store_review)

@bp.route('/login', methods=('GET',))
def login_try():
    return render_template('login.html')

'''
주의! 우리는 지난 시간에 회원가입/로그인을 빠르게 다루면서, 비밀번호 암호화에 대해 언급하지 않았습니다.
이 부분에 대해서는 다음 시간에 자세하게 설명하도록 할게요!!
우선, DB에서 데이터를 가져와서 비교하고, 비밀번호가 일치한다면 session 을 활성화 시킨다 정도만 이해하시면 됩니다.
'''

@bp.route('/login', methods=('POST',))
def login():
    id = request.form['user_id']
    password = request.form['password']

    user_data = rabbitUser.query.filter_by(id=id).first()

    if not user_data:
        flash("존재하지 않는 아이디입니다.")
        return redirect(url_for('main.login_try'))
    elif not checkpw(password.encode("utf-8"), user_data.password):
        flash("아이디와 비밀번호가 일치하지 않습니다.")
        return redirect(url_for('main.login_try'))
    else:
        session.clear()
        session['user_id'] = id
        session['nickname'] = user_data.nickname

        flash("안녕하세요, {}님!".format(user_data.nickname))

        return redirect(url_for('main.home'))

@bp.route('/register')
def join():
    return render_template('register.html')

@bp.route('/logout')
def logout():
    session.clear()
    flash("로그아웃 되었습니다.")
    return redirect(url_for('main.home'))

@bp.route('/register', methods=('POST',))
def register():
    if request.method == 'POST':
        user = rabbitUser.query.filter_by(id=request.form['user_id']).first()
        if not user:
            password = hashpw(request.form['password'].encode('utf-8'), gensalt())

            user = rabbitUser(id=request.form['user_id'], password=password,
            nickname=request.form['nickname'], telephone=request.form['telephone'])
            db.session.add(user)
            db.session.commit()
            
        else:
            flash("이미 가입된 아이디입니다.")
            return "이미 가입된 아이디입니다."

        return redirect(url_for('main.home'))

@bp.route('/write_review/<int:store_id>', methods=('POST',))
def create_review(store_id):
    if request.method == 'POST':
        review = rabbitReview(user_id=session['user_id'], store_id=store_id,
        rating=int(request.form['star']), content=request.form['review'])
        db.session.add(review)
        db.session.commit()

    flash("리뷰가 성공적으로 작성되었습니다.")
    return redirect(url_for('main.store_detail', store_id=store_id))

@bp.route('/delete_review/<int:store_id>/<int:review_id>')
def delete_review(store_id, review_id):
    review_info = rabbitReview.query.filter_by(id=review_id).first()
    
    if review_info.user_id != session['user_id']:
        flash("삭제할 권한이 없습니다.")
    else:
        db.session.delete(review_info)
        db.session.commit()
        flash("삭제가 완료되었습니다.")

    return redirect(url_for('main.store_detail', store_id=store_id))
    

web2/rabbit_delivery/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark border-bottom" style="background-color: #7979D3;">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">배달의 토끼</a>
        <button
            class="navbar-toggler ml-auto"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            {% if session['user_id'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <span class="nav-link" style="color:white;">안녕하세요! {{ session['nickname']}}님!</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.logout') }}">로그아웃</a>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.join') }}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.login') }}">로그인</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

web2/rabbit_delivery/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link
            rel="shortcut icon"
            href="{{ url_for('static', filename='favicon.ico') }}"
            type="image/x-icon"
        />
        <link
            rel="icon"
            href="{{ url_for('static', filename='favicon.ico') }}"
            type="image/x-icon"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='bootstrap.min.css') }}"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='my_styles.css') }}"
        />
        <!-- 각 html 페이지 타이틀  -->
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- 부트스트랩 내비게이션 포함 -->
        {% include "_navbar.html" %} {% block content %}
        <div class="container my-3">
            {% for message in get_flashed_messages() %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}

            <!-- 각 페이지의 내용이 들어감 -->
            {% block page_content %} {% endblock %}
        </div>
        {% endblock %}
    </body>
</html>

web2/rabbit_delivery/templates/login.html
{% extends "base.html" %}

{% block page_content %}
    {%for message in get_flashed_messages()%}
        <div class="alert alert-info">
            {{ message }}
        </div>
{% endfor %}

    <form action="{{ url_for('main.login') }}" method="post">
        <div class="form-group">
            <label for="user_id">아이디</label>
            <input class="form-control" type="text" name="user_id" id="user_id" placeholder="아이디 입력" >
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input class="form-control" name="password" type="password" placeholder="비밀번호 입력">
        </div>
        <input class="btn btn-primary" type="submit" value="로그인!">
    </form>
{% endblock %}

web2/rabbit_delivery/templates/main.html
{% extends "base.html" %}

{% block title %} 메인페이지 {% endblock %}

{% block page_content %}
    {% if store_list %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul class="list-group">
                    {% for store in store_list%}
                        <a style="all:unset;" href="/store/{{ store.id }}"> <li class="list-group-item list-group-item-action">{{ store.name }}</li></a>
                    {% endfor %}
                    </ul>
            </div>
        </div>
    </div>
    {% else %}
        <p>가게가 없어요...</p>
    {% endif %}

{% endblock %}

web2/rabbit_delivery/templates/register.html
{% extends "base.html" %}

{% block page_content %}
<form action="{{ url_for('main.register') }}" method="post">
    <div class="form-group">
        <label for="user_id">아이디</label>
        <input class="form-control" id="user_id" name="user_id" type="text" placeholder="아이디 입력">
    </div>
    <div class="form-group">
        <label for="password">비밀번호</label>
        <input class="form-control" id="password" name="password" type="password" placeholder="비밀번호 입력">
    </div>
    <div class="form-group">
        <label for="nickname">아이디</label>
        <input class="form-control" id="nickname" name="nickname" placeholder="닉네임">
    </div>
    <div class="form-group">
        <label for="telephone">전화번호</label>
        <input class="form-control" id="telephone" name="telephone" placeholder="전화번호">
    </div>
    <input class="btn btn-primary" type="submit" value="회원가입">
</form>
{% endblock %}

web2/rabbit_delivery/templates/store_detail.html
{% extends "base.html" %}
{% block page_content %}
{% if store_info %}
    <p>가게 이름: {{ store_info.name }}</p>
    <p>가게 위치: {{ store_info.location }}</p>
    <p>가게 번호: {{ store_info.telephone }}</p>
    <p>가게 별점: {{ store_info.rating }}</p>
    <p>여는 시간: {{ store_info.open_time }}</p>
    <p>닫는 시간: {{ store_info.close_time }}</p>
    <p>찜: {{ store_info.stars }}</p>
    <hr>

    <div id='map' style="height:400px"></div>
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=4a16995009237ad418b0dc5a69dd5fcc&libraries=services"></script>
    <script>
        const container = document.getElementById('map');

    const option = { // 지도를 생성할 때 필요한 기본 옵션
        center: new kakao.maps.LatLng(37.124524535, 127.123123),
        level : 3, // 지도의 레벨 (확대, 축소 정도)
    };

    const map = new kakao.maps.Map(container, option);

    // Geolocation, Geocoding

    const geocoder = new kakao.maps.services.Geocoder();
    geocoder.addressSearch('서울 동작구 사당로23길 164', function(result, status) {

        if (status === kakao.maps.services.Status.OK) {
            const coords = new kakao.maps.LatLng(result[0].y, result[0].x);

            const marker = new kakao.maps.Marker({
                position: coords,
                text: '으어어',
            });

            const infoWindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px; text-align:center; padding:6px 0">{{ store_info.name }}</div>',
            });
            infoWindow.open(map, marker);

            map.setCenter(coords);
        }
    });

    </script>




    {% if store_menu %}
        <h3>메뉴</h3>
        <ul>
        {% for menu in store_menu %}
            <li>{{ menu.food_name }} ({{ menu.price }} 원, {{ menu.description }})</li>
        {% endfor %}
        </ul>
    {% endif %}
    <hr>
    <h3>리뷰</h3>
    <h5>현재 {{review_info|length}}개의 리뷰가 있습니다.</h5>
    {% for review in review_info %}
        <div>
            <p>
                <span>{{review.rating}}</span>{{ review.content }}
                {% if session['user_id'] == review.user_id %} 
                    <a class="btn btn-danger btn-sm" href="{{ url_for('main.delete_review', store_id=store_info.id, review_id=review.id)}}">삭제</a>
                {% endif %}
            </p>
        </div>
    {% endfor %}
    
    <hr>
    {% if session['user_id'] %}
    <h3>리뷰 작성</h3>
    <form action="{{ url_for('main.create_review', store_id=store_info.id) }}" method="post">
        <select name="star">
            <option value="1">1점</option>
            <option value="2">2점</option>
            <option value="3">3점</option>
            <option value="4">4점</option>
            <option value="5">5점</option>
        </select>
        <div class="form-group">
            <label for="review">리뷰</label>
            <input class="form-control" name="review" id="review" placeholder="리뷰를 작성해주세요."></input> 
        </div>
        <input class="btn btn-primary" type="submit" value="리뷰 올리기">
    </form>
    {% endif %}

{% endif %}
{% endblock %}